# Generated by Django 5.2 on 2025-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="scheduled_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Specify when to publish the post (optional).",
                null=True,
                verbose_name="scheduled at",
            ),
        ),
    ]
